version: '3.8'
# TODO- docker syntax and how it works
services:
  postgres:
    image: postgres:15
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: blog_website
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # data mounting
  redis:
    image: redis:7
    container_name: blog_redis
    restart: always
    ports:
      - '6379:6379'
volumes:
  pgdata:
